name: GitHub-Profile-3D-Contrib

on:
  schedule: # 00:15 kST == 13:15 UTC
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: HwangBBang
      - name: Commit & Push
        run: |
          git config user.name HwangBBang
          git config user.email h1009218@hufs.ac.kr
          git add -A .
          git commit -m "generated"
          git push
